# Generated by Django 5.2.1 on 2025-06-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
